# Generated by Django 3.1 on 2020-09-21 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200920_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='sondage',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
