# Generated by Django 3.1 on 2020-09-18 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Abonne',
        ),
    ]
