# Generated by Django 3.1 on 2020-09-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0004_abonneprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonneprofile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
