# Generated by Django 3.1 on 2020-09-30 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membres', '0005_abonneprofile_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonneprofile',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Abonné'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
