# Generated by Django 3.1 on 2020-09-15 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=200, null=True)),
                ('PHONE', models.CharField(max_length=200, null=True)),
                ('EMAIL', models.CharField(max_length=200, null=True)),
                ('DATE_CREATION', models.DateTimeField(auto_now_add=True, null=True)),
                ('STATUT', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='Actif', max_length=200, null=True)),
                ('VISAGE', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE_CREATION', models.DateTimeField(auto_now_add=True, null=True)),
                ('DATE_ECHEANCE', models.DateTimeField(null=True)),
                ('DESCRIPTION', models.TextField(null=True)),
                ('CATEGORY', models.CharField(choices=[('prediction_prix', 'Prédiction de prix'), ('seg_client', 'Segmentation des clients'), ('sondage', 'Sondages')], max_length=200, null=True)),
                ('STATUT', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('finie', 'Finie')], default='en_attente', max_length=200, null=True)),
                ('AUTEUR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client')),
            ],
        ),
    ]
