# Generated by Django 3.1 on 2020-09-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20200918_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='TITRE',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
