# Generated by Django 3.1 on 2020-09-20 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0005_commande_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='VISAGE',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Délégué'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
