# Generated by Django 3.1 on 2020-09-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20200924_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='valeur',
        ),
    ]
